baseurl: ''
host: '127.0.0.1'

prose:
  rooturl: ''
  siteurl: 'http://bmlp.github.io'
  relativeLinks: 'http://bmlp.github.io/links.jsonp'
  media: 'media'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /assets
    - /theme-orig
    - config.rb
    - Gemfile
    - Gemfile.lock
    - 404.html
  metadata:
    _posts:
      - name: "title"
        field:
          element: "hidden"
          value: "title"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""

    _posts/whatwedo:
      - name: "category"
        field:
          element: "hidden"
          value: "whatwedo"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"

    _posts/resources:
      - name: "category"
        field:
          element: "hidden"
          value: "resources"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"

    _posts/teammembers:
      - name: "category"
        field:
          element: "hidden"
          value: "teammembers"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"

    _posts/allies:
      - name: "category"
        field:
          element: "hidden"
          value: "allies"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "website"
        field:
          element: "text"
      - name: "logo"
        field:
          element: "text"
          help: "Provide a small logo image"

