baseurl: ''
host: '127.0.0.1'
permalink: pretty
markdown: rdiscount

prose:
  rooturl: ''
  siteurl: 'https://bmlp.github.io'
  relativeLinks: 'https://bmlp.github.io/links.jsonp'
  media: 'assets/img'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /assets
    - /theme-orig
    - config.rb
    - Gemfile
    - Gemfile.lock
    - 404.html
    - /sass
    - .gitignore
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""

    _posts/whatwedo:
      - name: "category"
        field:
          element: "hidden"
          value: "whatwedo"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "icon"
        field:
          element: "text"
          value: "flag"

    _posts/resources:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          placeholder: ""
      - name: "category"
        field:
          element: "hidden"
          value: "resources"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "fileorlink"
        field:
          label: "File or Link?"
          element: "select"
          help: "Indicate whether this resource is a file or a link"
          options:
            - file
            - link
      - name: "link"
        field:
          label: "Resource Link"
          element: "text"
          help: "If the resource is a link, provide the full url here"
      - name: "file"
        field:
          label: "File Path"
          element: "text"
          help: "The path to the uploaded file, such as file.pdf"
      - name: "fileformat"
        field:
          label: "Resource Format"
          element: "select"
          options:
            - name: PDF
              option: file-pdf-o
            - name: Word Document
              option: file-word-o
            - name: Presentation
              option: file-powerpoint-o
            - name: Image
              option: file-image-o

    _posts/teammembers:
      - name: "category"
        field:
          element: "hidden"
          value: "teammembers"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"

    _posts/allies:
      - name: "category"
        field:
          element: "hidden"
          value: "allies"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "website"
        field:
          label: "Website URL"
          element: "text"
          help: "Full website URL, such as http://www.anorganization.com"
      - name: "logo"
        field:
          label: "Logo Image"
          element: "text"
          help: "Provide a small logo image, such as nlg-logo.png"

