---
facebook: https://www.facebook.com/blackmovementlawproject
twitter: Black_MLP
mailchimp_form_url: "//bmlp.us11.list-manage.com/subscribe/post-json?u=4caff5c5b26c1b3239a668641&amp;id=16efa33510"
contactemail: info@bmlp.org
address_header: ''
